force-app/main/default/objects/Entitlement__c/Entitlement__c.object-meta.xml
<CustomObject>
    <label>Qualified Entitlement</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Entitlements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Entitlement__c/fields/Early_Bird__c.field-meta.xml
<CustomField>
    <fullName>Early_Bird__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Early Bird</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Entitlement__c/fields/Early_Bird_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Early_Bird_End_Date__c</fullName>
    <label>Early Bird End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Entitlement__c/fields/Entitlement_Article__c.field-meta.xml
<CustomField>
    <fullName>Entitlement_Article__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entitlement Article</label>
    <referenceTo>Entitlement_article__c</referenceTo>
    <relationshipName>Entitlements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Entitlement__c/fields/Scheme__c.field-meta.xml
<CustomField>
    <fullName>Scheme__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Scheme</label>
    <referenceTo>Scheme__c</referenceTo>
    <relationshipName>Entitlements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Entitlement__c/fields/Scheme_Slab__c.field-meta.xml
<CustomField>
    <fullName>Scheme_Slab__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Scheme Slab</label>
    <referenceTo>Scheme_Slab__c</referenceTo>
    <relationshipName>Entitlements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Entitlement_article__c/Entitlement_article__c.object-meta.xml
<CustomObject>
    <label>Entitlement Article</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entitlement Articles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Entitlement_article__c/fields/Article_Type__c.field-meta.xml
<CustomField>
    <fullName>Article_Type__c</fullName>
    <label>Article Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Top Up</fullName>
            </value>
            <value>
                <fullName>Compensation</fullName>
            </value>
            <value>
                <fullName>Travel</fullName>
            </value>
            <value>
                <fullName>Goods</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Entitlement_article__c/fields/Compensation__c.field-meta.xml
<CustomField>
    <fullName>Compensation__c</fullName>
    <label>Compensation %</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Entitlement_article__c/fields/Goods__c.field-meta.xml
<CustomField>
    <fullName>Goods__c</fullName>
    <label>Goods</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Microwave</fullName>
            </value>
            <value>
                <fullName>Refrigerator</fullName>
            </value>
            <value>
                <fullName>Television</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Entitlement_article__c/fields/Scheme__c.field-meta.xml
<CustomField>
    <fullName>Scheme__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Scheme</label>
    <referenceTo>Scheme__c</referenceTo>
    <relationshipName>Entitlement_articles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scheme__c/Scheme__c.object-meta.xml
<CustomObject>
    <label>Scheme</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Scheme #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schemes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Scheme__c/fields/Compensation__c.field-meta.xml
<CustomField>
    <fullName>Compensation__c</fullName>
    <inlineHelpText>Scheme compensation award</inlineHelpText>
    <label>Compensation %</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Scheme__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <inlineHelpText>Effective end date</inlineHelpText>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Scheme__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <inlineHelpText>Applicable products/groups</inlineHelpText>
    <label>Product Portfolio</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Group</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Scheme__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>Effective start date</inlineHelpText>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Scheme_Slab__c/Scheme_Slab__c.object-meta.xml
<CustomObject>
    <label>Scheme Slab</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scheme Slabs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Scheme_Slab__c/fields/Lower_Limit_Volume__c.field-meta.xml
<CustomField>
    <fullName>Lower_Limit_Volume__c</fullName>
    <label>Lower Limit Volume</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Scheme_Slab__c/fields/Scheme__c.field-meta.xml
<CustomField>
    <fullName>Scheme__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Scheme</label>
    <referenceTo>Scheme__c</referenceTo>
    <relationshipLabel>Scheme Slabs</relationshipLabel>
    <relationshipName>Scheme_Slabs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scheme_Slab__c/fields/Upper_Limit_Volume__c.field-meta.xml
<CustomField>
    <fullName>Upper_Limit_Volume__c</fullName>
    <label>Upper Limit Volume</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TPM_Incentives__c/TPM_Incentives__c.object-meta.xml
<CustomObject>
    <label>Qualified Dealer</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Qualified Dealers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TPM_Incentives__c/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <label>Dealer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Qualified Dealers</relationshipLabel>
    <relationshipName>Incentives</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TPM_Incentives__c/fields/Incentive_Goods__c.field-meta.xml
<CustomField>
    <fullName>Incentive_Goods__c</fullName>
    <label>Incentive Qualified</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Incentive_Qualified</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/TPM_Incentives__c/fields/Incentive_Value__c.field-meta.xml
<CustomField>
    <fullName>Incentive_Value__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Incentive Earned</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TPM_Incentives__c/fields/Invoice_Amount__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Invoice Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TPM_Incentives__c/fields/Scheme__c.field-meta.xml
<CustomField>
    <fullName>Scheme__c</fullName>
    <label>Scheme</label>
    <referenceTo>Scheme__c</referenceTo>
    <relationshipName>Incentives</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TPM_Sales_Summary__c/TPM_Sales_Summary__c.object-meta.xml
<CustomObject>
    <label>Sales Summary</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Sales Summary #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Summary</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TPM_Sales_Summary__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Invoice Amount</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TPM_Sales_Summary__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TPM_Sales_Summary__c/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <label>Outlet</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sales Summary</relationshipLabel>
    <relationshipName>Sales</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TPM_Sales_Summary__c/fields/Incentive_Goods__c.field-meta.xml
<CustomField>
    <fullName>Incentive_Goods__c</fullName>
    <label>Incentive Qualified</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Incentive_Qualified</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/TPM_Sales_Summary__c/fields/Incentive_Value__c.field-meta.xml
<CustomField>
    <fullName>Incentive_Value__c</fullName>
    <label>Incentive Earned</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TPM_Sales_Summary__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <label>Group Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Premium</fullName>
                <default>true</default>
                <label>Premium</label>
            </value>
            <value>
                <fullName>Popular</fullName>
            </value>
            <value>
                <fullName>Prestige</fullName>
            </value>
            <value>
                <fullName>Luxuary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Product_Group.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Prestige</fullName>
        <default>true</default>
        <label>Prestige</label>
    </customValue>
    <customValue>
        <fullName>Popular</fullName>
    </customValue>
    <customValue>
        <fullName>Luxuary</fullName>
        <label>Luxury</label>
    </customValue>
    <customValue>
        <fullName>Premium</fullName>
    </customValue>
    <masterLabel>Product Group</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/getBenefitsCustom.cls
global class getBenefitsCustom implements Database.Batchable<sObject>, Database.stateful {

  private Integer counterSS = 0;
  
  global Integer recordsProcessed = 0;
  global Map<Integer, Scheme_Slab__c> Scheme_Slab = new Map<Integer, Scheme_Slab__c>();
  global Map<Integer, List<Entitlement__c>> Entitlement = new Map<Integer, List<Entitlement__c>>();
  global Map<Id, Entitlement_article__c> Entitlement_article = new Map<Id, Entitlement_article__c>();
  global Scheme__c schemeProcessed; 
   
  global String setMultiSelect (String value, String new_value)
  {
      if (String.isNotEmpty(value))
      {
          value = value + ';' + new_value;
          return value;
      }
      else
      {
          return new_value;
      }
  }
  global getBenefitsCustom (Id schemeId){
    List<Id> entilement_article_Ids= new List<Id>();
    List<Entitlement__c> entitlement_for_slab = new List<Entitlement__c>();
    
    schemeProcessed = [SELECT  Title__c,  Product_Group__c,  Start_Date__c,  End_Date__c FROM Scheme__c WHERE Id =:schemeId];
    
    counterSS = 0;
    for(Scheme_Slab__c objSS : [Select Id, Lower_Limit_Volume__c, Upper_Limit_Volume__c From Scheme_Slab__c WHERE Scheme__c =:schemeId]){
        Scheme_Slab.put(counterSS, objSS); 
        System.debug('>>>> SCHEME SLAB INITIATION ' + Scheme_Slab);
        entitlement_for_slab = [SELECT  Entitlement_Article__c,  Early_Bird__c,  Early_Bird_End_Date__c,  Scheme_Slab__c FROM Entitlement__c WHERE Scheme_Slab__c = :Scheme_Slab.get(counterSS).Id];
        Entitlement.put(counterSS,entitlement_for_slab);
        
        for(Entitlement__c  idValue : entitlement_for_slab){
            entilement_article_Ids.add(idValue.Entitlement_Article__c);
         }
         
         for(Entitlement_Article__c objEA : [SELECT  Name,  Article_Type__c,  Compensation__c,  Goods__c FROM Entitlement_article__c WHERE Id IN :entilement_article_Ids]){
             Entitlement_article.put(objEA.Id, objEA);
         }
     counterSS = counterSS + 1;     
     } 
  }
  
  // The batch job starts 
  global Database.Querylocator start(Database.BatchableContext bc){
    String soql = 'SELECT  Date__c,  Product_Group__c,  Amount__c, Incentive_Value__c, Incentive_Goods__c, Distributor__c FROM TPM_Sales_Summary__c WHERE Date__c >= ' +  String.ValueOf(schemeProcessed.Start_Date__c).left(10)  + 
    ' AND Date__c <= ' + String.ValueOf(schemeProcessed.End_Date__c).left(10) +  
    ' AND Product_Group__c = ' + '\'' + schemeProcessed.Product_Group__c + '\'';
    
    System.debug('SOQL ' + soql);
    
    //String soql = 'SELECT  Date__c, Distributor__c, Product_Group__c,  Amount__c, Incentive_Value__c, Incentive_Goods__c FROM TPM_Sales_Summary__c WHERE Product_Group__c = ' + '\'' + schemeProcessed.Product_Group__c + '\''; //+ ' LIMIT 40000';
    System.debug('>>>> execute ' + soql);
    return Database.getQuerylocator(soql);
    } 
  
  // The batch job executes and operates on one batch of records
  global void execute(Database.BatchableContext bc, List<TPM_Sales_Summary__c> scope){
    Decimal Calculated_Incentive_Value;
    List<Id> Qualified_Distributor_List = new List<Id>();
    TPM_Incentives__c Incentive_Updates;
    Map<Id, TPM_Incentives__c> Qualified_Entitlement = new Map<Id, TPM_Incentives__c>(); 
    
    for(TPM_Sales_Summary__c qualified_orders : scope)
     {
        qualified_orders.Incentive_Value__c = 0;
        qualified_orders.Incentive_Goods__c = '';
        Calculated_Incentive_Value = 0;
        // Create a distinct 
        if (!Qualified_Distributor_List.contains(qualified_orders.Distributor__c))
        {
            Qualified_Distributor_List.add(qualified_orders.Distributor__c);
        }
        //System.debug('>>>> QUALIFIED DEALERS ' + Qualified_Distributor_List);
        //System.debug('>>>> SCHEME SLAB ' + Scheme_Slab);
        for (Integer key : Scheme_Slab.keySet())
        {
            //System.debug ('ID ' + qualified_orders.Id + ' has $' + qualified_orders.Amount__c + ' inv. amount with slab lower: ' + Scheme_Slab.get(key).Lower_Limit_Volume__c + ' and slab higher' + Scheme_Slab.get(key).Upper_Limit_Volume__c); 
            if (qualified_orders.Amount__c >= Scheme_Slab.get(key).Lower_Limit_Volume__c && qualified_orders.Amount__c <= Scheme_Slab.get(key).Upper_Limit_Volume__c)
            {
                 for (Entitlement__c current_entitlement : Entitlement.get(key))
                 {
                     if ((current_entitlement.Early_Bird__c == false) || (current_entitlement.Early_Bird__c == true && qualified_orders.Date__c <= current_entitlement.Early_Bird_End_Date__c))
                     {
                         if (Entitlement_article.get(current_entitlement.Entitlement_Article__c).Article_Type__c == 'Compensation')
                         {
                             // compensation processing:
                             Calculated_Incentive_Value = Calculated_Incentive_Value + (qualified_orders.Amount__c * (Entitlement_article.get(current_entitlement.Entitlement_Article__c).Compensation__c)/100);
                             qualified_orders.Incentive_Value__c = Calculated_Incentive_Value;
                             qualified_orders.Incentive_Goods__c = setMultiSelect(qualified_orders.Incentive_Goods__c, Entitlement_article.get(current_entitlement.Entitlement_Article__c).Name);
                             System.debug ('ID ' + qualified_orders.Id + ' has $' + qualified_orders.Incentive_Value__c);       
                         }
                         else
                         {
                             // non-compensation processing:
                             qualified_orders.Incentive_Goods__c = setMultiSelect(qualified_orders.Incentive_Goods__c, Entitlement_article.get(current_entitlement.Entitlement_Article__c).Name);
                         } 
                     }
                 }
            }
        }
     }
     
     for (TPM_Incentives__c objCS : [SELECT Id, Incentive_Value__c, Incentive_Goods__c, Invoice_Amount__c, Distributor__c FROM TPM_Incentives__c WHERE  Scheme__c =: schemeProcessed.Id AND Distributor__c IN :Qualified_Distributor_List]){
         objCS.Incentive_Goods__c = '';
         objCS.Incentive_Value__c = 0;
         objCS.Invoice_Amount__c = 0;
         Qualified_Entitlement.put(objCS.Distributor__c, objCS);
     }
        
     //System.debug('>>>> Size Of Qualified Entitlement (TPM_Incentives__c) ' + Qualified_Entitlement.size());
     if (!Qualified_Entitlement.isEmpty())
     {
         //System.debug('>>>> Qualified Entitlement (TPM_Incentives__c) IS NOT EMPTY');
         for(TPM_Sales_Summary__c qualified_orders : scope)  
         {
             if (Qualified_Entitlement.containsKey(qualified_orders.Distributor__c))
             {
                 System.debug('>>>> Qualified Entitlement (TPM_Incentives__c) UNDER PROCESS ' + Qualified_Entitlement.get(qualified_orders.Distributor__c));
                 Incentive_Updates = Qualified_Entitlement.get(qualified_orders.Distributor__c);
                 Incentive_Updates.Incentive_Value__c = Incentive_Updates.Incentive_Value__c + qualified_orders.Incentive_Value__c;
                 Incentive_Updates.Invoice_Amount__c = Incentive_Updates.Invoice_Amount__c + qualified_orders.Amount__c;
                 System.debug('>>>> AMOUNT FOR DIS ' + Incentive_Updates.Distributor__c + ' IS ' + Incentive_Updates.Invoice_Amount__c );
                 
                 
                 if(String.isEmpty(Incentive_Updates.Incentive_Goods__c))
                 {
                     Incentive_Updates.Incentive_Goods__c = '';
                 }
                 
                 
                 //Incentive_Updates.Incentive_Goods__c = '';
                 System.debug('>>>> COMPARISON -OUT ' + Incentive_Updates.Incentive_Goods__c + '*--*' + qualified_orders.Incentive_Goods__c);
                 System.debug('>>>> RESULT -OUT ' + Incentive_Updates.Incentive_Goods__c.contains(qualified_orders.Incentive_Goods__c));
                
                
                 List<String> multi_select_element = qualified_orders.Incentive_Goods__c.split(';');
                 for(String element : multi_select_element)
                 {
                    if (!Incentive_Updates.Incentive_Goods__c.contains(element))
                     {
                         System.debug('>>>> COMPARISON -IN' + Incentive_Updates.Incentive_Goods__c + '*--*' + element);
                         System.debug('>>>> RESULT -IN' + Incentive_Updates.Incentive_Goods__c.contains(element));
                         Incentive_Updates.Incentive_Goods__c = setMultiSelect(Incentive_Updates.Incentive_Goods__c, element);
                     }
                 }
                 
                 Qualified_Entitlement.remove(qualified_orders.Distributor__c);
                 Qualified_Entitlement.put(qualified_orders.Distributor__c, Incentive_Updates);
             }
         }
         
         Database.SaveResult[] lsr = Database.update(Qualified_Entitlement.values());
         for (Database.SaveResult SR : lsr) {
            if (!SR.isSuccess()) {
                System.debug('Record:' + SR.getErrors()[0].getMessage() + '<br/>');
            }
         }
     }

     update (scope);
     recordsProcessed  = recordsProcessed  + scope.size();
  }
  // The batch job finishes
  global void finish(Database.BatchableContext bc){
  // Get the ID of the AsyncApexJob representing this batch job from Database.BatchableContext.    
  // Query the AsyncApexJob object to retrieve the current job's information.  

      AsyncApexJob a = [Select Id, Status,ExtendedStatus,NumberOfErrors, JobItemsProcessed,
      TotalJobItems, CreatedBy.Email
      from AsyncApexJob where Id =:BC.getJobId()];
        
       
       
      // Send an email to the Apex job's submitter notifying of job completion.  
      Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
      String[] toAddresses = new String[] {a.CreatedBy.Email};
      mail.setToAddresses(toAddresses);
      mail.setSubject('Incentive Calculations ' + a.Status);
      mail.setPlainTextBody('The batch Apex job processed ' + a.TotalJobItems +
      ' batches with '+ a.NumberOfErrors + ' failures. ' + recordsProcessed + ' invoices processed for incentive payout.');
      Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
  }
}